name: copy files

on: [push]
jobs:

  build:
    name: build
    runs on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

        name: copy file
        uses: canastro/copy-file-action@main:
        with:
          source: "rep1/text.txt"
          target: "newtext.txt"
